name: Post a welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: make a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.ref }}
          PR_NR: ${{ github.ref.run }}
          GH_URL: $GITHUB_SERVER_URL
          REPO_URL: ${{ github.event.pull }}
        run: gh pr comment $PR_URL --body "We will rock repositories."

