name: Post a welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: make a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.ref }}
          PR_NR: $GITHUB_RUN_NUMBER
          GH_URL: $GITHUB_SERVER_URL
          REPO_URL: ${{ github.repository }}
        run: gh pr comment $GH_URL/$REPO_URL/pull/$PR_NR --body "We will rock repositories."

