name: Post a welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: make a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.ref }}
          GH_URL: ${{ github.server.url }}
          REPO_URL: ${{ github.repository }}
        run: gh pr comment $GH_URL/$REPO_URL/$PR_URL --body "We will rock repositories."

