name: Post a welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: make a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.ref }}
        run: gh pr comment $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/$PR_URL --body "We will rock repositories."

